language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - pip install -U setuptools
  - pip install pytest --upgrade
script:
  - python setup.py install
  - coverage run --source flask_combo_jsonapi -m pytest -v
after_success:
  - coveralls

# TODO: create separate jobs for tests and deploy
